try:
    import cupy as xp
    HAS_GPU = True
    print("NVIDIA CUDA Cores Engaged: Array Batching Active (Performance)")
except ImportError:
    import numpy as xp
    HAS_GPU = False
    print("CPU Fallback: Standard Vectorization Active (Performance)")
import time
import streamlit as st
import json
import typer
from dynamic_memory_cache import DynamicMemoryCache
shared_cache = DynamicMemoryCache(percentage=0.47)
st.set_page_config(page_title="Flight Operations Dashboard", layout="wide", page_icon="✈️")
from control_bridge.performance_bridge import crank_performance
if __name__ == "__main__":
    crank_performance() 
    logging.basicConfig(filename="flight_system.log", level=logging.ERROR)
    app()
from flight_control_dynamics import FlightControlDynamics
import logging
import os
import numpy as np  # Added for state vectors
from textual.app import App, ComposeResult
from textual.widgets import Header, Footer, Static, Input, RichLog, Checkbox
from textual.containers import Vertical, Horizontal
from telemetry_link import TelemetryDispatcher
from waypoint_manager import WaypointManager
from export_telemetry import TelemetryDispatcher as GlobalDispatcher
from schema_validator import validate_configuration
import aviation_physics
import rossby_model
import fog_thermodynamics
import time
import radiation_model
if __name__ == "__main__":
    master_boot_sequence():
    """
    Enforces a strict loading order to prevent race conditions 
    between CUDA, Numba, and Physics kernels.
    """
    logger = logging.getLogger("MasterBoot")
    logger.info("Initializing Hardware Anchor (NVidia/Cuda)...")
    try:
        import numba.cuda
        numba.cuda.get_current_device().reset()
    except Exception as e:
        logger.warning(f"CUDA Hardware not found, proceeding with CPU fallback: {e}")
    logger.info("Pre-allocating Memory Cache...")
    import memory_manager
    memory_manager.preallocate_buffer(size_mb=2048)
    logger.info("Compiling NJIT Kernels...")
    import aviation_physics
    aviation_physics.warmup_kernels()
    logger.info("Loading Aviation Logic Modules...")
    global WaypointManager, FlightControlDynamics
    from waypoint_manager import WaypointManager
    from flight_control_dynamics import FlightControlDynamics
    logger.info("SYSTEM READY: Flight systems ready for taxi, flight, and landing. Pilot must operate landing gear and toe brakes.")
    app() # Launch your TUI
from intent_engine import IntentEngine
from collision_avoidance_app import CollisionMonitor
def load_telemetry_state(filepath="telemetry_frame.json"):
    """ Else-less data loader. Reads what the Physics Engine left behind. """
    
    """ GUARD 1: File not yet generated by the backend """
    if not os.path.exists(filepath):
        return {}
        
    """ GUARD 2: JSON Read Collision (Backend is currently writing to it) """
    try:
        with open(filepath, "r") as file:
            payload = json.load(file)
        return payload
    except (json.JSONDecodeError, PermissionError):
        return {}


def write_pilot_command(command_key, command_value, filepath="command_bus.json"):
    """ Asynchronously drops pilot inputs into a file for the FSM to read on its next 120Hz tick. """
    payload = {}
    
    """ Safely load existing commands without erasing them """
    if os.path.exists(filepath):
        try:
            with open(filepath, "r") as file:
                payload = json.load(file)
        except (json.JSONDecodeError, PermissionError):
            pass
            
    payload[command_key] = command_value
    
    """ Push to disk """
    try:
        with open(filepath, "w") as file:
            json.dump(payload, file, indent=4)
        return True
    except PermissionError:
        return False

def avionics_safety_wrapper(func):
    """Isolates physics/IO from the TUI event loop."""
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except Exception as e:
            logging.error(f"SYSTEM FAULT: {e}")
            return None
    return wrapper
# Inside your main application loop:
telemetry = root_manager.process_airport_arrival("KSEA", "16L/34R", 210.0, 150.0, 22.0, 340.0, mode="hold")

# 1. Dispatch Audio Warning
broadcast_atc_holding_clearance(telemetry)

# 2. Extract Numba Arrays for Core Guidance Execution
np_array_wp = root_manager.get_numba_compatible_waypoints(telemetry)

# 3. Archive the Telemetry
export_to_nasa_hdf5("flight_log.h5", 1042, telemetry, np_array_wp)

""" --- 3. DASHBOARD RENDERING ENGINE --- """
def render_glass_cockpit():
    """ Master UI layout. """
    
    st.title("Cyber-Physical Flight Operations Center")
    st.markdown("**(Asynchronous Telemetry Viewer - Hardware Isolated)**")
    
    """ Fetch the live JSON bus """
    live_data = load_telemetry_state()
    
    """ Initialize synthetic defaults if the 120Hz engine hasn't written yet """
    nav_data = live_data.get("navigation", {})
    env_data = live_data.get("environment", {})
    threat_data = live_data.get("threat_management", {})
    
    """ --- ROW 1: PRIMARY FLIGHT DISPLAY (PFD) --- """
    st.subheader("Primary Flight Metrics")
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.metric("Altitude (MSL)", f"{nav_data.get('altitude_ft', 0.0):.1f} ft")
    with col2:
        st.metric("Indicated Airspeed", f"{nav_data.get('ias_kts', 0.0):.1f} kts")
    with col3:
        st.metric("Current Pitch", f"{nav_data.get('pitch_deg', 0.0):.2f}°")
    with col4:
        st.metric("FSM Authority Mode", str(live_data.get("authority", {}).get("fsm_mode", "STANDBY")))

    st.divider()

    """ --- ROW 2: TACTICAL AVOIDANCE & ENVIRONMENTAL RADAR --- """
    col_rad, col_env = st.columns(2)
    
    with col_rad:
        st.subheader("Target Tracking (ACAS X)")
        active_alert = threat_data.get("active_alert", {})
        
        """ GUARD 1: No active threats """
        if not active_alert:
            st.success("Airspace Clear. No converging tracks detected.")
            
        """ HAPPY PATH: Threat detected """
        if active_alert:
            st.error(f"THREAT DETECTED: {active_alert.get('target_id', 'UNKNOWN')}")
            st.write(f"**Distance:** {active_alert.get('distance_m', 0.0):.1f} meters")
            st.write(f"**Time-To-Impact:** {active_alert.get('time_to_impact_sec', 0.0):.1f} sec")
            st.write(f"**ACAS Resolution:** {active_alert.get('acas_resolution', 'PENDING')}")
            
            """ Asynchronous Control Hook """
            if st.button("ACKNOWLEDGE & EXECUTE EVASION"):
                write_pilot_command("evade_target_id", active_alert.get("target_id"))
                st.toast("Evasion command pushed to asynchronous JSON bus.")

    with col_env:
        st.subheader("Environmental Shielding")
        icing_status = env_data.get("icing_status", {})
        wind_status = env_data.get("wind_dynamics", {})
        
        st.write(f"**Structural Ice Mass:** {icing_status.get('ice_mass_kg', 0.0):.2f} kg")
        st.write(f"**Wind Shear Warning:** {'ACTIVE' if wind_status.get('microburst_detected') else 'None'}")
        st.write(f"**Crosswind Component:** {wind_status.get('crosswind_kts', 0.0):.1f} kts")
        
        """ Asynchronous Control Hook """
        if st.button("ACTUATE PNEUMATIC BOOTS"):
            write_pilot_command("trigger_deicing", True)
            st.toast("De-icing request pushed to physics loop.")
            
class AviationConsole(App):
    CSS = """
    Screen { align: center middle; }
    #control-panel { width: 30%; height: 100%; border: solid green; }
    #log-panel { width: 70%; height: 100%; border: solid white; }
    .collision-alert { border: solid red; color: red; text-style: bold; }
    """
    BINDINGS = [
        ("q", "quit", "Quit"),
        ("d", "dispatch_telemetry", "Dispatch Global Telemetry"),
        ("m", "run_master_physics", "Run Boeing Master Sequence"),
        ("s", "scan_trajectory", "Scan for Collisions")
    ]
    def __init__(self, mode: str, target: str):
        super().__init__()
        self.mode = mode
        self.target = target
        self.current_pos = np.array([6371000.0, 0.0, 0.0])
        self.current_vel = np.array([7500.0, 0.0, 0.0])
    def compose(self) -> ComposeResult:
        """Merged compose method to prevent overwrite bug and apply CSS."""
        yield Header()
        yield Horizontal(
            Vertical(
                Static("FLIGHT CONSOLE", id="header"),
                Checkbox("Enable S-Turn Energy Management", id="s-turn-toggle"),
                Input(placeholder="Override: KEY=VAL", id="input"),
                Static("Status: NOMINAL", id="status"),
                Static("COLLISION RADAR: STANDBY", id="radar-status"),
                id="control-panel"
            ),
            RichLog(id="log-panel", highlight=True),
        )
        yield Footer()
    def on_mount(self):
        self.logger = self.query_one(RichLog)
        self.logger.write(f"SYSTEM BOOT: [Mode: {self.mode}] [Target: {self.target}]")
        try:
            self.nav = WaypointManager()
            self.computer = FlightControlDynamics(mode=self.mode)
            self.dispatcher = GlobalDispatcher(output_dir="logs")
            self.intent = IntentEngine()
            self.collision_monitor = CollisionMonitor(catalog_path="src/catalog-3.23.dat")
            self.logger.write("SUCCESS: Avionics & Radar Engines Linked.")
        except Exception as e:
            self.logger.write(f"CRITICAL: Init Failed: {e}")
    def on_checkbox_changed(self, event: Checkbox.Changed):
        """Selector logic: Updates the WaypointManager state."""
        if event.checkbox.id == "s-turn-toggle":
            if hasattr(self, 'nav'):
                self.nav.set_s_turn_mode(event.value)
            self.logger.write(f"S-Turn Selector: {'ON' if event.value else 'OFF'}")
    @avionics_safety_wrapper
    def on_input_submitted(self, event: Input.Submitted):
        """Processes manual overrides with safety checks for bad input formatting."""
        input_val = event.value.strip()
        if "=" in input_val:
            key, val = input_val.split("=", 1)
            self.logger.write(f"PARAM_UPDATE: {key} -> {val}")
            self.query_one("#status").update(f"ACTIVE: {key.upper()} SET")
        else:
            self.logger.write("ERROR: Input must be in KEY=VAL format.")
        self.query_one("#input").value = ""
    def action_dispatch_telemetry(self):
        payload = {"temp_c": 15.0, "alt": 3000, "target": self.target}
        self.dispatcher.dispatch(payload)
        self.logger.write("DISPATCH: Boeing, NASA, Lockheed, Axiom, Northrop, OAAM.")
    def action_run_master_physics(self):
        self.logger.write("SEQUENCE: Executing Boeing Thermodynamics...")
        fog_thermodynamics.run_fog_layer()
        rossby_model.run_rossby_layer()
        radiation_model.run_radiation_layer()
        self.logger.write("SEQUENCE: Physics layers synced.")
    @avionics_safety_wrapper
    def action_scan_trajectory(self):
        """Executes the Intent -> Collision radar scan pipeline."""
        self.logger.write(">>> INITIATING TRAJECTORY INTENT SCAN...")
        planned_path = self.nav.export_planned_trajectory(self.current_pos, self.current_vel)
        if not planned_path:
            self.logger.write("Radar: No active target path to scan.")
            return
        refined_intent = self.intent.calculate_maneuver_envelope(planned_path)
        collision_risk = self.collision_monitor.evaluate_risk(refined_intent)
        status_widget = self.query_one("#radar-status")
        if collision_risk['imminent']:
            self.logger.write(f"!!! COLLISION WARNING: Object {collision_risk['object_id']} at T-{collision_risk['time_to_impact']}s !!!")
            status_widget.update("RADAR: COLLISION IMMINENT")
            status_widget.add_class("collision-alert")
        else:
            self.logger.write("Radar: Trajectory Clear.")
            status_widget.update("RADAR: CLEAR")
            status_widget.remove_class("collision-alert")
app = typer.Typer()
@app.command()
def start(
    mode: str = typer.Option("TACTICAL", help="Flight Profile"),
    target: str = typer.Option("Earth", help="Destination")
):
    """Initialize the integrated aviation knowledge console."""
    console = AviationConsole(mode=mode, target=target)
    console.run()
if __name__ == "__main__":
    render_glass_cockpit()
    """ Automatic refresh handler for dashboard telemetry simulation """
    time.sleep(1.0)
    st.rerun()
    logging.basicConfig(filename="flight_system.log", level=logging.ERROR)
    app()
